apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artificial-intelligence-api-pvc
  namespace: artificial-intelligence-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi