apiVersion: v1
kind: Secret
metadata:
  name: artifical-intelligence-api-secret
  namespace: artificial-intelligence-api
type: Opaque
stringData:
  PG_HOSTNAME: "YOUR PG HOSTNAME"
  PG_USERNAME: "YOUR PG USERNAME"
  PG_PASSWORD: "YOUR PG PASSWORD"
  PG_DATABASE: "YOUR PG DATABASE"
  REDIS_HOSTNAME: "YOUR REDIS HOSTNAME"
  REDIS_PASSWORD: "YOUR REDIS PASSWORD"
  REDIS_PREFIX: "YOUR REDIS PREFIX"
  REDIS_USER: "YOUR REDIS USER"
  ENCRYPTION_KEY: "YOUR ENCRYPTION KEY"
  BLIND_INDEX_KEY: "YOUR BLIND INDEX KEY"
  JWT_SECRET: "YOUR JWT SECRET"
  GOOGLE_CLIENT_ID: "YOUR GOOGLE CLIENT ID"
  GOOGLE_REDIRECT_URI: "YOUR GOOGLE REDIRECT URI"
  GOOGLE_AUTH_URL: "YOUR GOOGLE AUTH URL"
  GOOGLE_HMAC: "YOUR GOOGLE HMAC"
  GOOGLE_TOKEN_URL: "YOUR GOOGLE TOKEN URL"
  GOOGLE_CLIENT_SECRET: "YOUR GOOGLE CLIENT SECRET"
  LANGFUSE_SECRET_KEY: "YOUR LANGFUSE SECRET KEY"
  LANGFUSE_PUBLIC_KEY: "YOUR LANGFUSE PUBLIC KEY"
  LANGFUSE_BASE_URL: "YOUR LANGFUSE BASE URL"
